name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Update apt
        run: sudo apt upgrade
      - name: Update sqlite3 
        run: sudo apt install sqlite3
      - name: Check sqlite3 version
        run: sqlite3 --version
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Build database
        run: poetry run invoke build
      - name: Run tests
        run: poetry run coverage run --branch -m pytest
      - name: Coverage report
        run: poetry run coverage xml
      - name: Coverage report to Codecov
        run: bash <(curl -s https://codecov.io/bash)
      - name: Run pylint
        run: poetry run invoke lint
